### ISSUE TITLE
HateoasAwareSpringDataWebConfiguration proxyBeanMethods=false error

### ISSUE THREAD

**Issue by String123** [spring-projects-experimental/spring-graalvm-native#367] opened 2020-11-19 09:14 UTC
Fatal error:java.lang.IllegalStateException: java.lang.IllegalStateException: ERROR: in 'org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration' these methods are directly invoking methods marked @Bean: [sortResolver, pageableResolver] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:480)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:349)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:508)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:114)
Caused by: java.lang.IllegalStateException: ERROR: in 'org.springframework.data.web.config.HateoasAwareSpringDataWebConfiguration' these methods are directly invoking methods marked @Bean: [sortResolver, pageableResolver] - due to the enforced proxyBeanMethods=false for components in a native-image, please consider refactoring to use instance injection.
        at org.springframework.graalvm.type.Type.verifyComponent(Type.java:2269)
        at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1282)
        at org.springframework.graalvm.support.ResourcesHandler.processTypesToFollow(ResourcesHandler.java:1349)
        at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1292)
        at org.springframework.graalvm.support.ResourcesHandler.processTypesToFollow(ResourcesHandler.java:1349)
        at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:1292)
        at org.springframework.graalvm.support.ResourcesHandler.processType(ResourcesHandler.java:960)
        at org.springframework.graalvm.support.ResourcesHandler.checkAndRegisterConfigurationType(ResourcesHandler.java:950)
        at org.springframework.graalvm.support.ResourcesHandler.processSpringFactory(ResourcesHandler.java:849)
        at org.springframework.graalvm.support.ResourcesHandler.processSpringFactories(ResourcesHandler.java:714)
        at org.springframework.graalvm.support.ResourcesHandler.register(ResourcesHandler.java:130)
        at org.springframework.graalvm.support.SpringFeature.beforeAnalysis(SpringFeature.java:110)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:693)
        at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:693)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:163)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1558)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1308)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1269)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1228)

**Comment by sdeleuze** [comment] 2020-11-19 10:35
@String123 Could you share what version of `spring-data-commons` are you using please?

**Comment by ericbv** [comment] 2020-11-19 18:43
@sdeleuze I'm experiencing the same error when trying to run `mvn spring-boot:build-image` on the petclinic-jpa sample. 
Version of spring-data-commons  is 2.4.1

**Comment by sdeleuze** [comment] 2020-11-19 19:27
Ok so that's the version shipped with Spring Boot 2.4.0. I don't see it in `petclinic-jpa`, are you using Spring Data REST or Spring HATEOAS? Are you using `spring-graalvm-native` 0.8.3-SNAPSHOT?

**Comment by String123** [comment] 2020-11-20 02:06
@sdeleuze Version of spring-data-commons is 2.4.1.Version of GraalVM is 20.3.Version of spring-graalvm-native is 0.8.3-SNAPSHOT.Version of jdk is 11.

**Comment by sdeleuze** [comment] 2020-11-20 06:53
Could one of you provide a repro project ?

**Comment by String123** [comment] 2020-11-20 07:09
@sdeleuze https://github.com/String123/spring-native-jpa-demo.git

**Comment by ericbv** [comment] 2020-11-20 07:35
For me this happens with an unmodified version of the current petclinic-jpa sample on this Repo. 
I've also tried is on a different machine, exact same error.

Reprodution steps:
- Checkout current version
- cd to petclinic-jpa version
- mvn spring-boot:build-image

For me mvn spring-boot:build-image is not using GraalVM  20.2.0 it seems to be GraalVM 20.3.0, I'm seeing this in the log output:

```
[INFO]     [creator]       Native Image: Contributing to layer
[INFO]     [creator]         GraalVM Version 20.3.0 (Java Version 1.8.0_272-b10)
```

**Comment by String123** [comment] 2020-11-20 08:50
@sdeleuze @ericbv The problem is solved after installing WSL2-Linux-Kernel for my Win 10 system.

**Comment by sdeleuze** [comment] 2020-11-20 11:26
I confirm this issue which only happens in buildpacks cc @nebhale.

**Comment by sdeleuze** [comment] 2020-11-20 12:50
For some reason I know see this error on CI (yeah CI is back) https://ci.spring.io/teams/spring-graalvm-native/pipelines/spring-graalvm-native/jobs/build-20.3-dev-java11-samples/builds/12

**Comment by sdeleuze** [comment] 2020-11-20 16:08
[Latest build](https://ci.spring.io/teams/spring-graalvm-native/pipelines/spring-graalvm-native/jobs/build-20.3-dev-java11-samples/builds/14) so not sure that's something that fully reproducible.

**Comment by aclement** [comment] 2020-11-20 21:54
Believed fixed. Two issues at play:
- Unpredictability. This is actually caused due to a TODO in the code we hadn't gotten around to, supporting split packages when resolving types. This originally was a very low priority (what fool splits a package...) *but* because of how we handle hints on package visible types, we have split packages in spring-graalvm-native.  Depending on what order they ended up in... it would have issues finding types. graalvm-native has a split package on `org.springframework.data.web.config`. So if graalvm-native was first and the real spring-data-commons later - we can resolve things. If graalvm-native is after spring-data-commons we would only look in it to resolve types in that package, not find them and fail assuming they were (incorrectly) unresolvable. Hence behaviour varying.  I've added split package support.

- Actual issue. Well, yeah, the inter bean detection needs more smarts. In this particular case once it was predictable it was always failing but we were incorrectly checking bridge methods which are methods generated to call themselves.  We are now skipping them.

It is also currently skipping lambdas (now) - may want to revisit that later. So it will be missing an inter bean method if invoked from a lambda context.

**Closed by aclement** 2020-11-20 21:54 UTC
Labels: type: regression
