### ISSUE TITLE
AWS Lambda  - GraalVM image Runtime error

### ISSUE THREAD

**Issue by renecairo** [spring-projects-experimental/spring-graalvm-native#123] opened 2020-05-08 17:00 UTC
Hi,

I'm trying to run the **function-aws** sample of yours as an AWS Lambda Function by providing a Custom Runtime and uploading the generated **function-aws-0.0.1-SNAPSHOT-native-zip.zip** file (containing the bootstrap and the function-aws files). The compiled file runs fine in my local environment, but in AWS I'm having the following error:

`{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 14922e1e-7d5d-42b6-9f04-9605accbe92b Error: Runtime exited with error: exit status 126"
}`

What I'm I missing in order to make it work in the Cloud?
Thanks in advance!

**Comment by dsyer** [comment] 2020-05-09 05:28
Works for me. Did you set the function name? How did you trigger it (what was the payload)?

**Comment by dsyer** [comment] 2020-05-09 05:30
From the Bash reference guide:

 >  If a command is found but is not executable, the return status is 126.

So that’s the problem. Are you on windows maybe? Not sure how to set the executable bit there.

**Comment by renecairo** [comment] 2020-05-12 16:48
Hi @dsyer 

I'm sorry for the late reply. We manage to make it work and started building on top of it, adding more complexity to the project by connecting to a MongoDB database (and eventually will add Redis and Elasticsearch capabilities). In the logs we see the replica-set discovered and connections being opened, but are receiving the following error at the end:

`START RequestId: cba83a16-b831-4782-a9ba-8982794cdb06 Version: $LATEST
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationContextInitializer : org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:445)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:427)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:420)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:272)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:253)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.example.reactive.ReactiveApplication.main(ReactiveApplication.java:22)
Caused by: java.lang.NoSuchMethodException: org.springframework.cloud.function.adapter.aws.CustomRuntimeInitializer.<init>()
	at java.lang.Class.getConstructor0(DynamicHub.java:3349)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:440)
	... 7 more
END RequestId: cba83a16-b831-4782-a9ba-8982794cdb06
REPORT RequestId: cba83a16-b831-4782-a9ba-8982794cdb06	Duration: 60.91 ms	Billed Duration: 100 ms	Memory Size: 512 MB	Max Memory Used: 11 MB	
RequestId: cba83a16-b831-4782-a9ba-8982794cdb06 Error: Runtime exited with error: exit status 1
Runtime.ExitError
`

Any idea on how to tackle this issue?
Thanks in advance

**Comment by dsyer** [comment] 2020-05-12 17:33
I don't see MongoDB in any of our samples yet, so I have no idea if that will work. The error you show here is independent of that though. It looks like you haven't used the Spring Graal Feature because your native image is missing some reflection configuration for a class that we know is in `spring.factories`. You might have to dig into it yourself a bit more, or provide some steps to reproduce so we can see it fail locally. Can you run your native image locally (i.e. not in AWS)?

**Comment by sdeleuze** [comment] 2020-11-03 10:18
Closing this issue since no feedback for a long time.

**Closed by sdeleuze** 2020-11-03 10:18 UTC
