### ISSUE TITLE
Failed to instantiate AnnotationConfigApplicationContext

### ISSUE THREAD

**Issue by gonella** [spring-projects-experimental/spring-graalvm-native#146] opened 2020-05-26 18:02 UTC
GraalVM		: 20.1.0 (Java Version 1.8.0_252)
Maven		: 3.6.3
spring-graal-native: [0.7.0.BUILD](https://repo.spring.io/libs-snapshot/org/springframework/experimental/spring-graal-native/0.7.0.BUILD-SNAPSHOT)

I'm facing an issue when executing the command "./build.sh" over sample project, [vanilla-orm](https://github.com/spring-projects-experimental/spring-graalvm-native/tree/master/spring-graalvm-native-samples/vanilla-orm). 

* Exception
> com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
>  org.springframework.util.unit.DataSize was unintentionally initialized at build time. To see why org.springframework.util.unit.DataSize got initialized use -H:+TraceClassInitialization
>         at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
>         at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:518)
>         at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)

Changing a little bit [compile.sh](https://github.com/spring-projects-experimental/spring-graalvm-native/blob/master/spring-graalvm-native-samples/vanilla-orm/compile.sh), adding the following lines below I was able to see a different exception. 

* New lines added
> -H:+TraceClassInitialization \
>   --initialize-at-build-time=org.springframework.util.unit.DataSize \
>   --report-unsupported-elements-at-runtime \
>   --allow-incomplete-classpath \

* Last exception: 

> May 26, 2020 1:47:41 PM org.springframework.boot.SpringApplication reportFailure
> SEVERE: Application run failed
> org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.annotation.AnnotationConfigApplicationContext]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>()
>         at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:146)
>         at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:588)
>         at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
>  

**Any idea what it could be wrong here?** 

Note: 
- I noticed "n" parameter used in mvn was not RECOGNIZED, so I removed from line below. 
`mvn -ntp package > target/native-image/output.txt`
- Running vanilla-orm as spring boot `mvn spring-boot-:run` is working.

**Comment by aclement** [comment] 2020-05-28 20:50
The `DataSize` issue is a sign that the feature isn't working at all properly. There is no need to set the initialize-at-build-time - there is a more fundamental problem than that which needs solving. hmm.

The ntp flag for maven is only available on up to date versions of maven :
```
-> mvn --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
-> mvn --help | grep ntp
 -ntp,--no-transfer-progress            Do not display transfer progress
```
It is harmless if you remove it but cuts down on the output for our builds. If you are on maven 3.6.3 I'm surprised it isn't working though, weird. 

What OS are you on? I'm on Mac and our build system is on Linux. 

A build just now of it worked ok:
```
 ./build.sh
=== Building vanilla-orm sample ===
Packaging vanilla-orm with Maven
May 28, 2020 1:35:33 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version 5.4.15.Final
Unpacking vanilla-orm-0.0.1.BUILD-SNAPSHOT.jar
Compiling vanilla-orm with GraalVM Version 20.1.0 (Java Version 1.8.0_252)
SUCCESS
Testing executable 'vanilla-orm'
SUCCESS
Build memory: 12.79GB
Image build time: 327.2s
RSS memory: 127.2M
Image size: 132.0M
Startup time: 0.148 (JVM running for 0.151)
```
Any errors in the target/native-image/output.txt file before the native image step? I just tried again with ntp removed from the maven step, that worked too.

**Comment by sdeleuze** [comment] 2020-11-03 10:15
`DataSize` issue indicates a misuse of `spring-graalvm-native` and the issue is old so I close it.

**Closed by sdeleuze** 2020-11-03 10:15 UTC
